name: Sync Repo
on:
  push:
    branches:
      - '*'
  workflow_dispatch: # Manual dispatch

jobs:
  sync-repo-to-codeberg:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: "Gather facts"
        run: |
          echo "Repo variables:"
          echo "  CODEBERG_REPO_URL: ${{ vars.CODEBERG_REPO_URL }}"
          echo "  CODEBERG_USERNAME: ${{ secrets.CODEBERG_USERNAME }}"
      - name: "Sync repo"
        uses: antonyho/mirror-action@master
        with:
          REMOTE: ${{ vars.CODEBERG_REPO_URL }}
          GIT_USERNAME: ${{ secrets.CODEBERG_USERNAME }}
          GIT_PASSWORD: ${{ secrets.CODEBERG_TOKEN }}
